// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFf5L7WQ8U6bevzQRuPAhWAB4cYfAjjY',
    appId: '1:776088824700:web:bee392a8a159baef8852f9',
    messagingSenderId: '776088824700',
    projectId: 'antic-4f981',
    authDomain: 'antic-4f981.firebaseapp.com',
    storageBucket: 'antic-4f981.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xN1xgUf14pb9_LwuY83luHtJR0zVTeE',
    appId: '1:776088824700:android:3fce161181a67b018852f9',
    messagingSenderId: '776088824700',
    projectId: 'antic-4f981',
    storageBucket: 'antic-4f981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl6YqXVIQlduSPkStdxn5z2B8EEwZrRaM',
    appId: '1:776088824700:ios:ec2b5b913021380b8852f9',
    messagingSenderId: '776088824700',
    projectId: 'antic-4f981',
    storageBucket: 'antic-4f981.appspot.com',
    iosClientId: '776088824700-173oge8h3ljloev3f3p39iie6krrgvve.apps.googleusercontent.com',
    iosBundleId: 'com.example.antic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl6YqXVIQlduSPkStdxn5z2B8EEwZrRaM',
    appId: '1:776088824700:ios:5128a6d63dfeb26e8852f9',
    messagingSenderId: '776088824700',
    projectId: 'antic-4f981',
    storageBucket: 'antic-4f981.appspot.com',
    iosClientId: '776088824700-imhq6oko3k38unb8am4nfukskt728f0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.antic.RunnerTests',
  );
}
